routes/web.php
    return view("admin/error");

});
Route::group(['prefix' =>'/admin','namespace' => 'Dashboard', 'middleware' => 'auth:admin'], function()
{
    Route::get('/','AdminController@index');

Route::get('/logout','LoginAdminController@destroy');
});
Route::group(['prefix' =>'/admin', 'middleware' => 'auth:admin'], function()
{
        Route::resource('/users','UserController');

     // ================================== Start Route categorys ===================================//
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['index']);
        Route::get('categorys/{id}/profile', 'Dashboard\CategoryController@show')->middleware('CheckRole:read-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['create','store'])->middleware('CheckRole:create-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['edit','update'])->middleware('CheckRole:edit-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['destroy'])->middleware('CheckRole:delete-categorys');
        Route::group(['middleware' => 'CheckRole:activate-categorys'], function(){
            Route::post('/categorys/{id}/activate', 'Dashboard\CategoryController@activate');
            Route::post('/categorys/{id}/deactivate', 'Dashboard\CategoryController@deactivate');
        });
        Route::post('/categorys/{id}/tags', 'Dashboard\CategoryController@addTag')->name('admin.addTag')->middleware('CheckRole:categorys-add-tag');
      // ==================================  End Route categorys ===================================//


     // =================================== Start Route products ===================================//
        Route::resource('products', 'Dashboard\ProductController')->only(['index']);
        Route::get('products/{id}/profile', 'Dashboard\ProductController@show')->middleware('CheckRole:read-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['create','store'])->middleware('CheckRole:create-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['edit','update'])->middleware('CheckRole:edit-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['destroy'])->middleware('CheckRole:delete-products');
        Route::group(['middleware' => 'CheckRole:activate-products'], function(){
            Route::post('/products/{id}/activate', 'Dashboard\ProductController@activate');
            Route::post('/products/{id}/deactivate', 'Dashboard\ProductController@deactivate');
        });
        Route::group(['middleware' => 'CheckRole:star-products'], function(){
            Route::post('/products/{id}/add_star_product', 'Dashboard\ProductController@add_star_product');
            Route::post('/products/{id}/del_star_product', 'Dashboard\ProductController@del_star_product');
        });
        Route::post('/products/{id}/tags', 'Dashboard\ProductController@addTag')->name('admin.addTag')->middleware('CheckRole:products-add-tag');
     // =================================== End Route products ===================================//


      // ==================================  Start Route shop_coupons ===================================//

   Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['index']);
        Route::get('shop_coupons/{id}/profile', 'Dashboard\ShopCouponController@show')->middleware('CheckRole:read-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['create','store'])->middleware('CheckRole:create-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['edit','update'])->middleware('CheckRole:edit-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['destroy'])->middleware('CheckRole:delete-shop-coupons');
        Route::group(['middleware' => 'CheckRole:activate-shop-coupons'], function(){
            Route::post('/shop_coupons/{id}/activate', 'Dashboard\ShopCouponController@activate');
            Route::post('/shop_coupons/{id}/deactivate', 'Dashboard\ShopCouponController@deactivate');
        });
      // ==================================  End Route shop_coupons ===================================//




        Route::get('/getAnimals', 'Dashboard\ProductController@getAnimals')->name('admin.getAnimals');



     // ================================== Start Route tags ===================================//
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['index']);
        Route::get('tags/{id}/profile', 'Dashboard\BlogTagController@show')->middleware('CheckRole:read-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['create','store'])->middleware('CheckRole:create-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['edit','update'])->middleware('CheckRole:edit-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['destroy'])->middleware('CheckRole:delete-tags');
        Route::group(['middleware' => 'CheckRole:activate-tags'], function(){
            Route::post('/tags/{id}/activate', 'Dashboard\BlogTagController@activate');
            Route::post('/tags/{id}/deactivate', 'Dashboard\BlogTagController@deactivate');
        });
      // ==================================  End Route tags ===================================//



     // ================================== Start Route citys ===================================//
        Route::resource('citys', 'Dashboard\CityController')->only(['index']);
        Route::get('citys/{id}/profile', 'Dashboard\CityController@show')->middleware('CheckRole:read-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['create','store'])->middleware('CheckRole:create-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['edit','update'])->middleware('CheckRole:edit-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['destroy'])->middleware('CheckRole:delete-citys');
        Route::group(['middleware' => 'CheckRole:activate-citys'], function(){
            Route::post('/citys/{id}/activate', 'Dashboard\CityController@activate');
            Route::post('/citys/{id}/deactivate', 'Dashboard\CityController@deactivate');
        });
      // ==================================  End Route citys ===================================//


     // ================================== Start Route regions ===================================//
        Route::resource('regions', 'Dashboard\RegionController')->only(['index']);
        Route::get('regions/{id}/profile', 'Dashboard\RegionController@show')->middleware('CheckRole:read-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['create','store'])->middleware('CheckRole:create-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['edit','update'])->middleware('CheckRole:edit-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['destroy'])->middleware('CheckRole:delete-regions');
        Route::group(['middleware' => 'CheckRole:activate-regions'], function(){
            Route::post('/regions/{id}/activate', 'Dashboard\RegionController@activate');
            Route::post('/regions/{id}/deactivate', 'Dashboard\RegionController@deactivate');
        });
      // ==================================  End Route regions ===================================//



     // ================================== Start Route locations ===================================//
        Route::resource('locations', 'Dashboard\LocationController')->only(['index']);
        Route::get('locations/{id}/profile', 'Dashboard\LocationController@show')->middleware('CheckRole:read-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['create','store'])->middleware('CheckRole:create-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['edit','update'])->middleware('CheckRole:edit-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['destroy'])->middleware('CheckRole:delete-locations');
        Route::group(['middleware' => 'CheckRole:activate-locations'], function(){
            Route::post('/locations/{id}/activate', 'Dashboard\LocationController@activate');
            Route::post('/locations/{id}/deactivate', 'Dashboard\LocationController@deactivate');
        });
      // ==================================  End Route locations ===================================//





     // ==================================  Start Route Blogs ==================================//
        Route::resource('blogs', 'Dashboard\BlogController')->only(['index']);
        Route::get('blogs/{id}/profile', 'Dashboard\BlogController@show')->middleware('CheckRole:read-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['create','store'])->middleware('CheckRole:create-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['edit','update'])->middleware('CheckRole:edit-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['destroy'])->middleware('CheckRole:delete-blog');
        Route::group(['middleware' => 'CheckRole:activate-blogs'], function(){
            Route::post('/blogs/{id}/activate', 'Dashboard\BlogController@activate');
            Route::post('/blogs/{id}/deactivate', 'Dashboard\BlogController@deactivate');
        });
        Route::post('/blogs/{id}/tags', 'Dashboard\BlogController@addTag')->name('admin.addTag')->middleware('CheckRole:blog-add-tag');
     // ==================================  End Route Blogs ================================== //

     // ==================================  Start Route product_sellers ================================== //

app/Models/ShopCoupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ShopCoupon extends Model 
{

    protected $table = 'shop_coupons';
    public $timestamps = true;

    protected $fillable= array('coupon_code','coupon_name','coupon_discount', 'status','expire_date');
    use SoftDeletes;

    protected $dates = ['deleted_at'];

}

app/Http/Controllers/Dashboard/ShopCouponController.php
<?php 

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\ShopCoupon;
use App\Http\Requests\ShopCouponRequest;
use Session;
class ShopCouponController extends Controller 
{

  public function index()
  {
    $shop_coupons=ShopCoupon::orderBy('id','DESC')->get();
    return view('admin.shop_coupons.index',compact('shop_coupons'));   
  }
  public function activate(Request $request, $id)
  {
    $status = ShopCoupon::findOrFail($id);
    $status->update(['status' => 1]);

    Session::flash('success','القسم مفعل الان');
    return Redirect('admin/shop_coupons');
  }

  public function deactivate(Request $request, $id)
  {
   $status = ShopCoupon::findOrFail($id);
   $status->update(['status' => 0]);
   Session::flash('success','القسم غير مفعل الان');
   return Redirect('admin/shop_coupons');
 }
 public function create()
 {
    return view('admin.shop_coupons.create');   
 }


  public function store(ShopCouponRequest $request)
  {
   try{
    $addshop_coupon=ShopCoupon::create([
      'coupon_code' => $request['coupon_code'],
      'coupon_name' => $request['coupon_name'],
      'coupon_discount' => $request['coupon_discount'],
    ]);
    return redirect()->route('shop_coupons.index')->with(['success' => 'تم الحفظ بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('shop_coupons.create')->with(['error' => 'يوجد خطأ']);

    }
  }
  

  public function edit($id)
  {
   $shop_coupon=ShopCoupon::find($id);
   if(! $shop_coupon)
   {
      return redirect()->route('shop_coupons.index')->with(['error' => 'لا توجد رساله بهذا العنوان']);
    } 
    return view('admin.shop_coupons.edit',compact('shop_coupon'));

  }

  public function update(Request $request, $id)
  {
    try{

      $shop_coupon_data=ShopCoupon::find($id);
      if(! $shop_coupon_data)
      {
        return  redirect()->route('shop_coupons.edit', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
      }
      ShopCoupon::where('id',$id)->update([
        'coupon_code' => $request['coupon_code'],
        'coupon_name' => $request['coupon_name'],
        'coupon_discount' => $request['coupon_discount'],

      ]);

      return redirect()->route('shop_coupons.index')->with(['success' => 'تم التعديل بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('shop_coupons.index')->with(['error' => 'يوجد خطأ']);

    }
  }


  public function destroy($id)
  {
   try{

    $shop_coupon=ShopCoupon::find($id);
    if(! $shop_coupon)
    {
      return  redirect()->route('shop_coupons', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
    } 
        $shop_coupon ->delete();

      return redirect()->route('shop_coupons.index')->with(['success' => 'تم الحذف بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('shop_coupons.index')->with(['error' => 'يوجد خطأ']);

    }
  }

}

?>

resources/views/admin/shop_coupons/create.blade.php
@extends('admin.layouts.master')
@section('css')
<!--- Internal Select2 css-->
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">كوبونات الخصم</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ إضافه كوبون جديد</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/shop_coupons')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض كوبونات الخصم</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  إضافه كوبون جديد
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                <form action="{{route('shop_coupons.store')}}" class="parsley-style-1" id="selectForm2" name="selectForm2"  method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-5" id="coupon_code">
                        <label>كود الخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_code" name="coupon_code" value="{{old('coupon_code')}}" maxlength ="6" placeholder="ادخل كود الخصم" required="" type="text">
                           @error('coupon_code')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-5 mg-t-20 mg-md-t-0" id="coupon_name">
                        <label>اسم الكود الخاص بالخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_name" name="coupon_name" value="{{old('coupon_name')}}" placeholder="ادخل اسم الكود الخاص بالخصم" required="" type="text">
                           @error('coupon_name')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-2 mg-t-20 mg-md-t-0" id="coupon_discount">
                        <label>نسبه الخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_discount" name="coupon_discount" value="{{old('coupon_discount')}}" placeholder="ادخل نسبه الخصم" required="" type="number"> %
                           @error('coupon_discount')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                    </div>
                  </div>
                  <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">إضافه</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Select2 js -->
<script src="{{URL::asset('public/assets/plugins/select2/js/select2.min.js')}}"></script>
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
@endsection

resources/views/admin/shop_coupons/edit.blade.php
@extends('admin.layouts.master')
@section('css')
<!--- Internal Select2 css-->
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">كوبونات الخصم</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ تعديل بيانات الكوبون</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/shop_coupons')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض كوبونات الخصم</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  تعديل بيانات  / {{$shop_coupon->coupon_name}}
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                 <form method="POST" class="parsley-style-1" id="selectForm2" name="selectForm2" enctype="multipart/form-data" role="form" action="{{route('shop_coupons.update', $shop_coupon->id)}}">
                    @csrf
                  {{ method_field('PUT') }}

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-5" id="coupon_code">
                        <label>كود الخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_code" name="coupon_code" value="{{$shop_coupon->coupon_code}}" required="" type="text">
                           @error('coupon_code')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-5 mg-t-20 mg-md-t-0" id="coupon_name">
                        <label>اسم الكود الخاص بالخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_name" value="{{$shop_coupon->coupon_name}}" name="coupon_name" required="" type="text">
                           @error('coupon_name')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-2 mg-t-20 mg-md-t-0" id="coupon_discount">
                        <label>نسبه الخصم: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#coupon_discount" value="{{$shop_coupon->coupon_discount}}" name="coupon_discount"  required="" type="number"> %
                           @error('coupon_discount')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>

                    </div>
                  </div>
                          

                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">حفظ</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Select2 js -->
<script src="{{URL::asset('public/assets/plugins/select2/js/select2.min.js')}}"></script>
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){

    $("#show").click(function(){
    $(".hide").show();
  });
  });
</script>
@endsection