routes/web.php
        Route::resource('products', 'Dashboard\ProductController')->only(['edit','update'])->middleware('CheckRole:edit-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['destroy'])->middleware('CheckRole:delete-products');
        Route::group(['middleware' => 'CheckRole:activate-products'], function(){
            Route::post('/products/{id}/activate', 'Dashboard\ProductController@activate');
            Route::post('/products/{id}/deactivate', 'Dashboard\ProductController@deactivate');
        });
        Route::group(['middleware' => 'CheckRole:star-products'], function(){
            Route::post('/products/{id}/add_star_product', 'Dashboard\ProductController@add_star_product');
            Route::post('/products/{id}/del_star_product', 'Dashboard\ProductController@del_star_product');
        });
        Route::post('/products/{id}/tags', 'Dashboard\ProductController@addTag')->name('admin.addTag')->middleware('CheckRole:products-add-tag');
     // =================================== End Route products ===================================//


      // ==================================  Start Route shop_coupons ===================================//

   Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['index']);
        Route::get('shop_coupons/{id}/profile', 'Dashboard\ShopCouponController@show')->middleware('CheckRole:read-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['create','store'])->middleware('CheckRole:create-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['edit','update'])->middleware('CheckRole:edit-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['destroy'])->middleware('CheckRole:delete-shop-coupons');
        Route::group(['middleware' => 'CheckRole:activate-shop-coupons'], function(){
            Route::post('/shop_coupons/{id}/activate', 'Dashboard\ShopCouponController@activate');
            Route::post('/shop_coupons/{id}/deactivate', 'Dashboard\ShopCouponController@deactivate');
        });
      // ==================================  End Route shop_coupons ===================================//




        Route::get('/getAnimals', 'Dashboard\ProductController@getAnimals')->name('admin.getAnimals');



     // ================================== Start Route tags ===================================//
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['index']);
        Route::get('tags/{id}/profile', 'Dashboard\BlogTagController@show')->middleware('CheckRole:read-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['create','store'])->middleware('CheckRole:create-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['edit','update'])->middleware('CheckRole:edit-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['destroy'])->middleware('CheckRole:delete-tags');
        Route::group(['middleware' => 'CheckRole:activate-tags'], function(){
            Route::post('/tags/{id}/activate', 'Dashboard\BlogTagController@activate');
            Route::post('/tags/{id}/deactivate', 'Dashboard\BlogTagController@deactivate');
        });
      // ==================================  End Route tags ===================================//



     // ================================== Start Route citys ===================================//
        Route::resource('citys', 'Dashboard\CityController')->only(['index']);
        Route::get('citys/{id}/profile', 'Dashboard\CityController@show')->middleware('CheckRole:read-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['create','store'])->middleware('CheckRole:create-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['edit','update'])->middleware('CheckRole:edit-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['destroy'])->middleware('CheckRole:delete-citys');
        Route::group(['middleware' => 'CheckRole:activate-citys'], function(){
            Route::post('/citys/{id}/activate', 'Dashboard\CityController@activate');
            Route::post('/citys/{id}/deactivate', 'Dashboard\CityController@deactivate');
        });
      // ==================================  End Route citys ===================================//


     // ================================== Start Route regions ===================================//
        Route::resource('regions', 'Dashboard\RegionController')->only(['index']);
        Route::get('regions/{id}/profile', 'Dashboard\RegionController@show')->middleware('CheckRole:read-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['create','store'])->middleware('CheckRole:create-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['edit','update'])->middleware('CheckRole:edit-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['destroy'])->middleware('CheckRole:delete-regions');
        Route::group(['middleware' => 'CheckRole:activate-regions'], function(){
            Route::post('/regions/{id}/activate', 'Dashboard\RegionController@activate');
            Route::post('/regions/{id}/deactivate', 'Dashboard\RegionController@deactivate');
        });
      // ==================================  End Route regions ===================================//



     // ================================== Start Route locations ===================================//
        Route::resource('locations', 'Dashboard\LocationController')->only(['index']);
        Route::get('locations/{id}/profile', 'Dashboard\LocationController@show')->middleware('CheckRole:read-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['create','store'])->middleware('CheckRole:create-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['edit','update'])->middleware('CheckRole:edit-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['destroy'])->middleware('CheckRole:delete-locations');
        Route::group(['middleware' => 'CheckRole:activate-locations'], function(){
            Route::post('/locations/{id}/activate', 'Dashboard\LocationController@activate');
            Route::post('/locations/{id}/deactivate', 'Dashboard\LocationController@deactivate');
        });
      // ==================================  End Route locations ===================================//





     // ==================================  Start Route Blogs ==================================//
        Route::resource('blogs', 'Dashboard\BlogController')->only(['index']);
        Route::get('blogs/{id}/profile', 'Dashboard\BlogController@show')->middleware('CheckRole:read-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['create','store'])->middleware('CheckRole:create-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['edit','update'])->middleware('CheckRole:edit-blog');
        Route::resource('blogs', 'Dashboard\BlogController')->only(['destroy'])->middleware('CheckRole:delete-blog');
        Route::group(['middleware' => 'CheckRole:activate-blogs'], function(){
            Route::post('/blogs/{id}/activate', 'Dashboard\BlogController@activate');
            Route::post('/blogs/{id}/deactivate', 'Dashboard\BlogController@deactivate');
        });
        Route::post('/blogs/{id}/tags', 'Dashboard\BlogController@addTag')->name('admin.addTag')->middleware('CheckRole:blog-add-tag');
     // ==================================  End Route Blogs ================================== //

     // ==================================  Start Route product_sellers ================================== //
        Route::resource('product_sellers', 'Dashboard\ProductSellerController')->only(['index']);
        Route::get('product_sellers/{id}/profile', 'Dashboard\ProductSellerController@show')->middleware('CheckRole:read-product_sellers');
        Route::resource('product_sellers', 'Dashboard\ProductSellerController')->only(['create','store'])->middleware('CheckRole:create-product_sellers');
        Route::resource('product_sellers', 'Dashboard\ProductSellerController')->only(['edit','update'])->middleware('CheckRole:edit-product_sellers');
        Route::resource('product_sellers', 'Dashboard\ProductSellerController')->only(['destroy'])->middleware('CheckRole:delete-product_sellers');
        Route::group(['middleware' => 'CheckRole:activate-sellers-products'], function(){
            Route::post('/product_sellers/{id}/activate', 'Dashboard\ProductSellerController@activate');
            Route::post('/product_sellers/{id}/deactivate', 'Dashboard\ProductSellerController@deactivate');
        });
     // ==================================  End Route product_sellers ================================== //


     // ==================================  Start Route product_arrivals ================================== //
        Route::resource('product_arrivals', 'Dashboard\ProductArrivalController')->only(['index']);
        Route::get('product_arrivals/{id}/profile', 'Dashboard\ProductArrivalController@show')->middleware('CheckRole:read-product_arrivals');
        Route::resource('product_arrivals', 'Dashboard\ProductArrivalController')->only(['create','store'])->middleware('CheckRole:create-product_arrivals');
        Route::resource('product_arrivals', 'Dashboard\ProductArrivalController')->only(['edit','update'])->middleware('CheckRole:edit-product_arrivals');
        Route::resource('product_arrivals', 'Dashboard\ProductArrivalController')->only(['destroy'])->middleware('CheckRole:delete-product_arrivals');
        Route::group(['middleware' => 'CheckRole:activate-arrivals-products'], function(){

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model 
{

    protected $table = 'citys';
    public $timestamps = true;

    protected $fillable=array('city_name_ar');

    public function Region()
    {
        return $this->hasMany('App\Models\Region', 'city_id');
    }


}

app/Http/Controllers/Dashboard/CityController.php
<?php 

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\City;
use App\Http\Requests\CityRequest;
use Session;
use Auth;
class CityController extends Controller 
{

  public function index()
  {
    $citys=City::orderBy('id','DESC')->get();
    return view('admin.citys.index',compact('citys'));   
  }
 //  public function activate(Request $request, $id)
 //  {
 //    $status = City::findOrFail($id);
 //    $status->update(['status' => 1]);

 //    Session::flash('success','الكلمه الدلاليه مفعل الان');
 //    return Redirect('admin/citys');
 //  }

 //  public function deactivate(Request $request, $id)
 //  {
 //   $status = City::findOrFail($id);
 //   $status->update(['status' => 0]);
 //   Session::flash('success','الكلمه الدلاليه غير مفعل الان');
 //   return Redirect('admin/citys');
 // }
 public function create()
 {
  return view('admin.citys.create');   
 }


  public function store(CityRequest $request)
  {
   try{
    $addCity=City::create([
      'city_name_ar' => $request['city_name_ar'],
    ]);
    return redirect()->route('citys.index')->with(['success' => 'تم الحفظ بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('citys.create')->with(['error' => 'يوجد خطأ']);

    }
  }
  

  public function edit($id)
  {
   $city=City::find($id);
   if(! $city)
   {
      return redirect()->route('citys.index')->with(['error' => 'لا توجد رساله بهذا العنوان']);
    } 
    return view('admin.citys.edit',compact('city'));

  }

  public function update(Request $request, $id)
  {
    try{

      $city_data=City::find($id);
      if(! $city_data)
      {
        return  redirect()->route('citys.edit', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
      }
      City::where('id',$id)->update([
        'city_name_ar' => $request['city_name_ar'],
      ]);

      return redirect()->route('citys.index')->with(['success' => 'تم التعديل بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('citys.index')->with(['error' => 'يوجد خطأ']);

    }
  }


  public function destroy($id)
  {
   try{

    $city=City::find($id);
    if(! $city)
    {
      return  redirect()->route('citys', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
    } 


    if(!($city->Region->isEmpty()))
    {
       return  redirect()->route('citys.index')->with(['error'=> 'لا يمكن الحذف هذه البيانات متعلقه بأخري ']);
    }
    $city ->delete();

      return redirect()->route('citys.index')->with(['success' => 'تم الحذف بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('citys.index')->with(['error' => 'يوجد خطأ']);

    }
  }

}

?>

resources/views/admin/citys/create.blade.php
@extends('admin.layouts.master')
@section('css')
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">المناطق</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ إضافه منطه جديد</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/citys')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض المناطق</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  إضافه منطه جديد
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                <form action="{{route('citys.store')}}" class="parsley-style-1" id="selectForm2" name="selectForm2"  method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="city_name_ar">
                        <label>اسم المنطه : <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#city_name_ar" name="city_name_ar" value="{{old('city_name_ar')}}" placeholder="ادخل اسم المنطه " required="" type="text">
                           @error('city_name_ar')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                     
                    </div>
                  </div>
             
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">إضافه</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
@endsection

resources/views/admin/citys/edit.blade.php
@extends('admin.layouts.master')
@section('css')
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">المناطق</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ تعديل بيانات المناطق</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/citys')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض المناطق</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  تعديل بيانات  / {{$city->city_name_ar}}
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                 <form method="POST" class="parsley-style-1" id="selectForm2" name="selectForm2" enctype="multipart/form-data" role="form" action="{{route('citys.update', $city->id)}}">
                    @csrf
                  {{ method_field('PUT') }}

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="city_name_ar">
                        <label>اسم المنطقه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#city_name_ar" name="city_name_ar" value="{{$city->city_name_ar}}" placeholder="Enter firstname" required="" type="text">
                           @error('city_name_ar')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
<!--                       <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="tag_en">
                        <label>اسم المناطق باللغه الانجليزيه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#tag_en" value="{{$city->tag_en}}" name="tag_en" placeholder="Enter lastname" required="" type="text">
                           @error('tag_en')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div> -->
                    </div>
                  </div>
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">حفظ</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
@endsection

resources/views/admin/citys/index.blade.php
@extends('admin.layouts.master')
@section('css')
<!-- Internal Data table css -->
<link href="{{URL::asset('public/assets/plugins/datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/jquery.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">

<style type="text/css">
  .buttons-pdf , .buttons-excel
  {
    display: none !important;
  }

  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
  .chk-option .checkbox-fade
  {
    display: inline-flex !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">المناطق</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ عرض كل المناطق</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            @permission(['create-citys']) 
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/citys/create')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i>إضافه المنطقه</a>
            </div>
     @endpermission
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

          <!--div-->
          <div class="col-xl-12">
            <div class="card mg-b-20">
              <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                  <h4 class="card-title mg-b-0">عرض كل المناطق</h4>
                  <i class="mdi mdi-dots-horizontal text-gray"></i>
                </div>
                <hr>
              </div>
               @if(Session::has('success'))
          <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
          @endif

          @if(Session::has('error'))
          <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
          @endif
              <div class="card-body">
                <div class="table-responsive">
                  <table id="example" class="table key-buttons text-md-nowrap">
                    <thead>
                      <tr>
                          <th class="border-bottom-0 text-center">#</th>
                          <th class="border-bottom-0 text-center">اسم المنطقه</th>
<!--                           <th class="border-bottom-0 text-center">حاله المنطقه</th>
 -->                         

                          @permission(['edit-citys'])
                          <th class="border-bottom-0 text-center">تعديل</th>
                          @endpermission
                          @permission(['delete-citys'])
                          <th class="border-bottom-0 text-center">حذف</th>
                          @endpermission
                           <th class="border-bottom-0 text-center">أنشأ في</th>
                      </tr>
                    </thead>
                    <tbody>
                        @isset($citys)
                          @php $count = 1; @endphp
                          @foreach($citys as $data)
                          <tr>

                            <td class="text-center">{{$count}}</td>
                            <td class="text-center">{{$data->city_name_ar}}</td>
                           <!--  <td class="text-center">
                              @if($data->status == 0)
                              <form method="POST" action="{{url('/admin/citys/'.$data->id.'/activate')}}">
                                @csrf
                                
                                <div class="chk-option">
                                  <div class="checkbox-fade fade-in-primary"> 
                                       <label class="ckbox mg-b-5"><input name="status" type="checkbox" onchange="this.form.submit()" ><span></span></label>

                                   </div>
                                 </div>
                               </form>
                               @else
                               <form method="POST" action="{{url('/admin/citys/'.$data->id.'/deactivate')}}">
                                @csrf

                                <div class="chk-option">
                                  <div class="checkbox-fade fade-in-primary"> 
                     <label class="ckbox mg-b-5"><input name="status" type="checkbox" onchange="this.form.submit()" checked><span></span></label>

                                 </div>
                               </div>
                             </form>
                             @endif
                           </td> -->
                           @permission(['edit-citys'])
                           <td class="text-center">
                             <a href="{{url('admin/citys/'.$data->id.'/edit')}}" class="btn btn-primary ti-pencil-alt"></a>
                           </td>
                             @endpermission 
                             @permission(['delete-citys'])
                           <td class="text-center">
                            <form method="post" action="{{url('admin/citys/'.$data->id)}}">
                              {{csrf_field()}}
                              <a class="btn btn-danger ti-trash" data-id="{{$data->id}}" data-toggle="modal" data-target="#delete-data{{$data->id}}"></a>
                              <!-- Modal -->
                              <div class="modal modal-danger fade" id="delete-data{{$data->id}}" role="dialog">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                   <div class="modal-header" style="    display: inline;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title text-center" style="float: right;" id="exampleModalLabel">تأكيد الحذف</h4>
                                  </div>

                                  <div class="modal-body">
                                    <h5 class="text-center ">هل انت متأكد من حذف   {{$data->city_name_ar}}؟</h5>                  
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-outline"  data-dismiss="modal">إلغاء</button>
                                    <input type="hidden" name="_method" value="delete">

                                    <button class="btn btn-outline danger delete pull-right">حذف</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </form>     
                        </td>
  @endpermission
                             <td class="text-center"> {{ ($data->created_at)->toDayDateTimeString()}}</td>

                      </tr>

                      @php $count ++; @endphp
                      @endforeach

                      @endisset
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--/div-->
        </div>
        <!-- /row -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!-- Internal Data tables -->
<script src="{{URL::asset('public/assets/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/jszip.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.html5.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
<!--Internal  Datatable js -->
<script src="{{URL::asset('public/assets/js/table-data.js')}}"></script>
@endsection