routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/welcome', function () {
    if(app()->getLocale() == 'ar')
    {
        echo 'f';
    }
    else
    {
        echo 'fs';
    }
   // dd(app()->getLocale());
    return view('welcome');
});




Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    
    // return what you want
    
});
Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:cache');
    
    // return what you want
    
});

Route::fallback(function () {

    return view("admin/error");

});
Route::group(['prefix' =>'/admin','namespace' => 'Dashboard', 'middleware' => 'auth:admin'], function()
{
    Route::get('/','AdminController@index');

Route::get('/logout','LoginAdminController@destroy');
});
Route::group(['prefix' =>'/admin', 'middleware' => 'auth:admin'], function()
{
        Route::resource('/users','UserController');

     // ================================== Start Route categorys ===================================//
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['index']);
        Route::get('categorys/{id}/profile', 'Dashboard\CategoryController@show')->middleware('CheckRole:read-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['create','store'])->middleware('CheckRole:create-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['edit','update'])->middleware('CheckRole:edit-categorys');
        Route::resource('categorys', 'Dashboard\CategoryController')->only(['destroy'])->middleware('CheckRole:delete-categorys');
        Route::group(['middleware' => 'CheckRole:activate-categorys'], function(){
            Route::post('/categorys/{id}/activate', 'Dashboard\CategoryController@activate');
            Route::post('/categorys/{id}/deactivate', 'Dashboard\CategoryController@deactivate');
        });
        Route::post('/categorys/{id}/tags', 'Dashboard\CategoryController@addTag')->name('admin.addTag')->middleware('CheckRole:categorys-add-tag');
      // ==================================  End Route categorys ===================================//


     // =================================== Start Route products ===================================//
        Route::resource('products', 'Dashboard\ProductController')->only(['index']);
        Route::get('products/{id}/profile', 'Dashboard\ProductController@show')->middleware('CheckRole:read-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['create','store'])->middleware('CheckRole:create-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['edit','update'])->middleware('CheckRole:edit-products');
        Route::resource('products', 'Dashboard\ProductController')->only(['destroy'])->middleware('CheckRole:delete-products');
        Route::group(['middleware' => 'CheckRole:activate-products'], function(){
            Route::post('/products/{id}/activate', 'Dashboard\ProductController@activate');
            Route::post('/products/{id}/deactivate', 'Dashboard\ProductController@deactivate');
        });
        Route::group(['middleware' => 'CheckRole:star-products'], function(){
            Route::post('/products/{id}/add_star_product', 'Dashboard\ProductController@add_star_product');
            Route::post('/products/{id}/del_star_product', 'Dashboard\ProductController@del_star_product');
        });
        Route::post('/products/{id}/tags', 'Dashboard\ProductController@addTag')->name('admin.addTag')->middleware('CheckRole:products-add-tag');
     // =================================== End Route products ===================================//


      // ==================================  Start Route shop_coupons ===================================//

   Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['index']);
        Route::get('shop_coupons/{id}/profile', 'Dashboard\ShopCouponController@show')->middleware('CheckRole:read-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['create','store'])->middleware('CheckRole:create-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['edit','update'])->middleware('CheckRole:edit-shop-coupons');
        Route::resource('shop_coupons', 'Dashboard\ShopCouponController')->only(['destroy'])->middleware('CheckRole:delete-shop-coupons');
        Route::group(['middleware' => 'CheckRole:activate-shop-coupons'], function(){
            Route::post('/shop_coupons/{id}/activate', 'Dashboard\ShopCouponController@activate');
            Route::post('/shop_coupons/{id}/deactivate', 'Dashboard\ShopCouponController@deactivate');
        });
      // ==================================  End Route shop_coupons ===================================//




        Route::get('/getAnimals', 'Dashboard\ProductController@getAnimals')->name('admin.getAnimals');



     // ================================== Start Route tags ===================================//
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['index']);
        Route::get('tags/{id}/profile', 'Dashboard\BlogTagController@show')->middleware('CheckRole:read-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['create','store'])->middleware('CheckRole:create-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['edit','update'])->middleware('CheckRole:edit-tags');
        Route::resource('tags', 'Dashboard\BlogTagController')->only(['destroy'])->middleware('CheckRole:delete-tags');
        Route::group(['middleware' => 'CheckRole:activate-tags'], function(){
            Route::post('/tags/{id}/activate', 'Dashboard\BlogTagController@activate');
            Route::post('/tags/{id}/deactivate', 'Dashboard\BlogTagController@deactivate');
        });
      // ==================================  End Route tags ===================================//



     // ================================== Start Route citys ===================================//
        Route::resource('citys', 'Dashboard\CityController')->only(['index']);
        Route::get('citys/{id}/profile', 'Dashboard\CityController@show')->middleware('CheckRole:read-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['create','store'])->middleware('CheckRole:create-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['edit','update'])->middleware('CheckRole:edit-citys');
        Route::resource('citys', 'Dashboard\CityController')->only(['destroy'])->middleware('CheckRole:delete-citys');
        Route::group(['middleware' => 'CheckRole:activate-citys'], function(){
            Route::post('/citys/{id}/activate', 'Dashboard\CityController@activate');
            Route::post('/citys/{id}/deactivate', 'Dashboard\CityController@deactivate');
        });
      // ==================================  End Route citys ===================================//


     // ================================== Start Route regions ===================================//
        Route::resource('regions', 'Dashboard\RegionController')->only(['index']);
        Route::get('regions/{id}/profile', 'Dashboard\RegionController@show')->middleware('CheckRole:read-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['create','store'])->middleware('CheckRole:create-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['edit','update'])->middleware('CheckRole:edit-regions');
        Route::resource('regions', 'Dashboard\RegionController')->only(['destroy'])->middleware('CheckRole:delete-regions');
        Route::group(['middleware' => 'CheckRole:activate-regions'], function(){
            Route::post('/regions/{id}/activate', 'Dashboard\RegionController@activate');
            Route::post('/regions/{id}/deactivate', 'Dashboard\RegionController@deactivate');
        });
      // ==================================  End Route regions ===================================//



     // ================================== Start Route locations ===================================//
        Route::resource('locations', 'Dashboard\LocationController')->only(['index']);
        Route::get('locations/{id}/profile', 'Dashboard\LocationController@show')->middleware('CheckRole:read-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['create','store'])->middleware('CheckRole:create-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['edit','update'])->middleware('CheckRole:edit-locations');
        Route::resource('locations', 'Dashboard\LocationController')->only(['destroy'])->middleware('CheckRole:delete-locations');
        Route::group(['middleware' => 'CheckRole:activate-locations'], function(){
            Route::post('/locations/{id}/activate', 'Dashboard\LocationController@activate');
            Route::post('/locations/{id}/deactivate', 'Dashboard\LocationController@deactivate');
        });
      // ==================================  End Route locations ===================================//





     // ==================================  Start Route Blogs ==================================//
        Route::resource('blogs', 'Dashboard\BlogController')->only(['index']);
        Route::get('blogs/{id}/profile', 'Dashboard\BlogController@show')->middleware('CheckRole:read-blog');

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.master')
@section('css')
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">الكلمات الدلاليه</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ إضافه كلمه دلاليه جديد</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/tags')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض الكلمات الدلاليه</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  إضافه كلمه دلاليه جديد
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                <form action="{{route('tags.store')}}" class="parsley-style-1" id="selectForm2" name="selectForm2"  method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="tag_ar">
                        <label>اسم الكلمه الدلاليه باللغه العربيه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#tag_ar" name="tag_ar" value="{{old('tag_ar')}}" placeholder="ادخل اسم الكلمه الدلاليه باللغه العربيه" required="" type="text">
                           @error('tag_ar')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="tag_en">
                        <label>اسم الكلمه الدلاليه باللغه الانجليزيه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#tag_en" name="tag_en" value="{{old('tag_en')}}" placeholder="ادخل اسم الكلمه الدلاليه باللغه الانجليزيه" required="" type="text">
                           @error('tag_en')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                    </div>
                  </div>
             
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">إضافه</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.master')
@section('css')
<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">الكلمات الدلاليه</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ تعديل بيانات الكلمه الدلاليه</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/tags')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض الكلمات الدلاليه</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  تعديل بيانات  / {{$tag->tag_ar}}
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                 <form method="POST" class="parsley-style-1" id="selectForm2" name="selectForm2" enctype="multipart/form-data" role="form" action="{{route('tags.update', $tag->id)}}">
                    @csrf
                  {{ method_field('PUT') }}

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="tag_ar">
                        <label>اسم الكلمه الدلاليه باللغه العربيه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#tag_ar" name="tag_ar" value="{{$tag->tag_ar}}" placeholder="Enter firstname" required="" type="text">
                           @error('tag_ar')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="tag_en">
                        <label>اسم الكلمه الدلاليه باللغه الانجليزيه: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#tag_en" value="{{$tag->tag_en}}" name="tag_en" placeholder="Enter lastname" required="" type="text">
                           @error('tag_en')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                    </div>
                  </div>
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">حفظ</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.master')
@section('css')
<!-- Internal Data table css -->
<link href="{{URL::asset('public/assets/plugins/datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/jquery.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">

<style type="text/css">
  .buttons-pdf , .buttons-excel
  {
    display: none !important;
  }

  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
  .chk-option .checkbox-fade
  {
    display: inline-flex !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">الكلمات الدلاليه</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ عرض كل الكلمات الدلاليه</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            @permission(['create-tags'])
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/tags/create')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i>إضافه كلمه دلاليه</a>
            </div>
            @endpermission
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

          <!--div-->
          <div class="col-xl-12">
            <div class="card mg-b-20">
              <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                  <h4 class="card-title mg-b-0">عرض كل الكلمات الدلاليه</h4>
                  <i class="mdi mdi-dots-horizontal text-gray"></i>
                </div>
                <hr>
              </div>
               @if(Session::has('success'))
          <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
          @endif

          @if(Session::has('error'))
          <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
          @endif
              <div class="card-body">
                <div class="table-responsive">
                  <table id="example" class="table key-buttons text-md-nowrap">
                    <thead>
                      <tr>
                          <th class="border-bottom-0 text-center">#</th>
                          <th class="border-bottom-0 text-center">اسم الكلمه دلاليه باللغه العربيه</th>
                           @permission(['activate-tags'])
                          <th class="border-bottom-0 text-center">حاله الكلمه دلاليه</th>
                          @endpermission
                          <th class="border-bottom-0 text-center">أنشأ في</th>
                          @permission(['edit-tags'])
                          <th class="border-bottom-0 text-center">تعديل</th>
                          @endpermission
                          @permission(['delete-tags'])
                          <th class="border-bottom-0 text-center">حذف</th>
                          @endpermission
                           <th class="border-bottom-0 text-center">اسم الكلمه دلاليه باللغه الانجليزيه :</th>
                      </tr>
                    </thead>
                    <tbody>
                        @isset($tags)
                          @php $count = 1; @endphp
                          @foreach($tags as $data)
                          <tr>

                            <td class="text-center">{{$count}}</td>
                            <td class="text-center">{{$data->tag_ar}}</td>
                            @permission(['activate-tags'])
                            <td class="text-center">
                              @if($data->status == 0)
                              <form method="POST" action="{{url('/admin/tags/'.$data->id.'/activate')}}">
                                @csrf
                                
                                <div class="chk-option">
                                  <div class="checkbox-fade fade-in-primary"> 
                                       <label class="ckbox mg-b-5"><input name="status" type="checkbox" onchange="this.form.submit()" ><span></span></label>

                                   </div>
                                 </div>
                               </form>
                               @else
                               <form method="POST" action="{{url('/admin/tags/'.$data->id.'/deactivate')}}">
                                @csrf

                                <div class="chk-option">
                                  <div class="checkbox-fade fade-in-primary"> 
                     <label class="ckbox mg-b-5"><input name="status" type="checkbox" onchange="this.form.submit()" checked><span></span></label>

                                 </div>
                               </div>
                             </form>
                             @endif
                           </td>
                           @endpermission
                           <td class="text-center"> {{ ($data->created_at)->toDayDateTimeString()}}</td>
                           @permission(['edit-tags'])
                           <td class="text-center">
                             <a href="{{url('admin/tags/'.$data->id.'/edit')}}" class="btn btn-primary ti-pencil-alt"></a>
                           </td>
                           @endpermission
                          @permission(['delete-tags'])
                           <td class="text-center">
                            <form method="post" action="{{url('admin/tags/'.$data->id)}}">
                              {{csrf_field()}}
                              <a class="btn btn-danger ti-trash" data-id="{{$data->id}}" data-toggle="modal" data-target="#delete-data{{$data->id}}"></a>
                              <!-- Modal -->
                              <div class="modal modal-danger fade" id="delete-data{{$data->id}}" role="dialog">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                   <div class="modal-header" style="    display: inline;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title text-center" style="float: right;" id="exampleModalLabel">تأكيد الحذف</h4>
                                  </div>

                                  <div class="modal-body">
                                    <h5 class="text-center ">هل انت متأكد من حذف   {{$data->tag_ar}}؟</h5>                  
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-outline"  data-dismiss="modal">إلغاء</button>
                                    <input type="hidden" name="_method" value="delete">

                                    <button class="btn btn-outline danger delete pull-right">حذف</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </form>     
                        </td>
                         @endpermission
                                                    <td class="text-center">{{$data->tag_en}}</td>

                      </tr>

                      @php $count ++; @endphp
                      @endforeach

                      @endisset
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--/div-->
        </div>
        <!-- /row -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!-- Internal Data tables -->
<script src="{{URL::asset('public/assets/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/jszip.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.html5.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
<!--Internal  Datatable js -->
<script src="{{URL::asset('public/assets/js/table-data.js')}}"></script>
@endsection