routes/web.php
            Route::post('/sliders/{id}/activate', 'Dashboard\SliderController@activate');
            Route::post('/sliders/{id}/deactivate', 'Dashboard\SliderController@deactivate');
        });
      // ==================================  End Route sliders ===================================//


     // ================================== Start Route trademarks ===================================//
        Route::resource('trademarks', 'Dashboard\TrademarkController')->only(['index']);
        Route::get('trademarks/{id}/profile', 'Dashboard\TrademarkController@show')->middleware('CheckRole:read-trademarks');
        Route::resource('trademarks', 'Dashboard\TrademarkController')->only(['create','store'])->middleware('CheckRole:create-trademarks');
        Route::resource('trademarks', 'Dashboard\TrademarkController')->only(['edit','update'])->middleware('CheckRole:edit-trademarks');
        Route::resource('trademarks', 'Dashboard\TrademarkController')->only(['destroy'])->middleware('CheckRole:delete-trademarks');
        Route::group(['middleware' => 'CheckRole:activate-trademarks'], function(){
            Route::post('/trademarks/{id}/activate', 'Dashboard\TrademarkController@activate');
            Route::post('/trademarks/{id}/deactivate', 'Dashboard\TrademarkController@deactivate');
        });
      // ==================================  End Route trademarks ===================================//


     // ================================== Start Route stores ===================================//
        Route::resource('stores', 'Dashboard\StoreController')->only(['index']);
        Route::get('stores/{id}/profile', 'Dashboard\StoreController@show')->middleware('CheckRole:read-stores');
        Route::resource('stores', 'Dashboard\StoreController')->only(['edit','update'])->middleware('CheckRole:edit-stores');
        Route::resource('stores', 'Dashboard\StoreController')->only(['destroy'])->middleware('CheckRole:delete-stores');
       
      // ==================================  End Route stores ===================================//


     // ================================== Start Route customers ===================================//
        Route::resource('customers', 'Dashboard\CustomerController')->only(['index']);
        Route::get('customers/{id}/profile', 'Dashboard\CustomerController@show')->middleware('CheckRole:read-customers');
        Route::resource('customers', 'Dashboard\CustomerController')->only(['create','store'])->middleware('CheckRole:create-customers');
        // Route::resource('customers', 'Dashboard\CustomerController')->only(['edit','update'])->middleware('CheckRole:edit-customers');
        // Route::resource('customers', 'Dashboard\CustomerController')->only(['destroy'])->middleware('CheckRole:delete-customers');
       
      // ==================================  End Route customers ===================================//


     // ================================== Start Route settings ===================================//
        
        Route::resource('settings', 'Dashboard\SettingController')->only(['index','update'])->middleware('CheckRole:edit-settings');
       
      // ==================================  End Route settings ===================================//

        
        Route::resource('customer_contacts', 'Dashboard\ContactController');


        Route::resource('customer_reviews', 'Dashboard\CustomerReviewController');


        Route::resource('users', 'Dashboard\UsersController');

        Route::resource('newsletters', 'Dashboard\NewsletterController');
});

Route::group(['namespace' => 'Dashboard','prefix' => 'admin', 'middleware' => 'guest:admin'], function()
{
    Route::get('/login','LoginAdminController@getLogin')->name( 'get.admin.login');
    Route::post('/login','LoginAdminController@login')->name( 'admin.login');
   

});

// Administrator & SuperAdministrator Control Panel Routes
Route::group(['prefix' => '/admin', 'middleware' => 'auth:admin', 'namespace' => 'Dashboard'], function () {
    Route::resource('/users', 'UsersController')->middleware('roles:superadministrator');
    Route::resource('/permission', 'PermissionController')->middleware('roles:superadministrator');
    Route::resource('/roles', 'RolesController')->middleware('roles:superadministrator');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// ============================================================================================================================================================================================================================================================== START WEBSITE ROUTES ==================================================================================== //



// ==================================  START WEBSITE ROUTES ================================== //
Route::group(['prefix' => LaravelLocalization::setLocale() ,'middleware' => ['localizationRedirect', 'localeViewPath']], function()
{

 
Route::get('comming-soon', function () {
    return view('site.comming-soon');
});


        Route::get('/','Website\SiteController@index')->name('site');
        Route::get('/about-us','Website\SiteController@get_about_page')->name('site.about-us');
        Route::get('/privacy-policy','Website\SiteController@get_privacy_page')->name('site.privacy-policy');


        Route::get('/contact-us','Website\SiteController@get_contact_page');
        Route::post('/contact-us/store','Website\SiteController@store_contact')->name('site.store_contact');

        Route::post('/newsletter/store','Website\SiteController@store_newsletter')->name('site.store_newsletter');

        Route::get('/clinic/{clinic_name}','Website\ClinicController@get_clinic')->name('site.clinic');

        Route::get('/hotel/{hotel_name}','Website\HotelController@get_hotel')->name('site.hotel');


        Route::get('/product/{code}', 'Website\ProductController@get_product');
        Route::get('/blogs', 'Website\BlogController@get_blogs')->name('site.sort1');
        Route::get('/blog/{blog_name}', 'Website\BlogController@get_singleblog');
        Route::get('/blogs/sortingP_p', 'Website\BlogController@sort2')->name('site.sort2');
       Route::get('/blogsTag/{tag_name}', 'Website\BlogController@get_blogs_tag');
       Route::get('/blogs-search', 'Website\BlogController@getBlogsSearch');

       Route::get('/search', 'Website\SiteController@getProductsSearch')->name('site.search');


Route::get('/category', 'Website\ProductController@get_category');
Route::get('/filter', 'Website\ProductController@get_category');
Route::get('/filter/{name}/{name2}', 'Website\ProductController@name');
Route::get('/filter/{name}', 'Website\ProductController@animal_name');

    Route::group(['middleware'=>'auth:customer'],function()
    {

        Route::get('/products/addFav', 'Website\ProductController@add_remove_product_to_fav')->name('site.add_fav');
       Route::get('/products/appraisal/{product_id}', 'Website\ProductController@store_appraisal')->name('site.store_appraisal');

        Route::get('/blog/comment/{blog_id}', 'Website\BlogController@store_comment')->name('site.store_comment');

        Route::get('/favourite', 'Website\ProductController@get_fav_products')->name('site.favourite_page');

        Route::get('/cart', 'Website\ProductController@get_cart_products')->name('site.cart_page');
        Route::get('/cart/update', 'Website\ProductController@update_cart')->name('site.update_cart');
        Route::get('/cart/removeCart', 'Website\ProductController@removeAllProductFromCart')->name('site.remove_cart');


        Route::post('/cart/update_bill', 'Website\ProductController@update_bill')->name('site.update_bill');

        Route::post('/cart/choose_payment_method', 'Website\ProductController@choose_payment_method')->name('site.choose_payment_method');
        Route::post('/cart/apply_discount', 'Website\ProductController@apply_discount')->name('apply_discount');




        Route::post('/clinic/add_more','Website\ClinicController@addMorePost');

        Route::post('/hotel/add_more','Website\HotelController@addMorePost');

        Route::post('/hotel/add_more','Website\HotelController@addMorePost');

        Route::get('/favourite/removeFav', 'Website\ProductController@removeProductFromFav')->name('site.remove_fav');

        Route::get('/cart/removeSingleCart', 'Website\ProductController@removeProductFromCart')->name('site.remove_single_cart');


        Route::get('/favourite/addCart', 'Website\ProductController@addProductToCart')->name('site.add_cart');

        
        Route::get('/profile', 'Website\CustomerController@get_profile');
        Route::any('/profile/{id}', 'Website\CustomerController@edit_customer')->name('edit-profile');
        Route::post('/update-photo/{id}', 'Website\CustomerController@update_photo')->name('update-photo');
        Route::post('/update-password/{id}', 'Website\CustomerController@update_password')->name('update-password');


        Route::get('/my-orders', 'Website\CustomerController@get_orders')->name('site.orders');
        Route::get('/my-orders-3', 'Website\CustomerController@get_last_3month')->name('site.orders-3');
        Route::get('/my-orders-6', 'Website\CustomerController@get_last_6month')->name('site.orders-6');


        Route::get('/my-reservations', 'Website\CustomerController@get_reservations')->name('site.reservations');
        Route::get('/my-reservations-3', 'Website\CustomerController@get_reserv_last_3month')->name('site.reservations-3');
        Route::get('/my-reservations-6', 'Website\CustomerController@get_reserv_last_6month')->name('site.reservations-6');
        Route::get('/my-reservations/removeReserv', 'Website\CustomerController@removeReservation')->name('site.remove_reserv');

        Route::get('/shippment-address', 'Website\CustomerController@shippment_address');

app/Http/Controllers/Dashboard/CustomerReviewController.php
<?php 

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\CustomerReview;
use App\Http\Requests\CustomerReviewRequest;
use Session;
class CustomerReviewController extends Controller 
{

  public function index()
  {
    $customer_reviews=CustomerReview::get();
    return view('admin.customer_reviews.index',compact('customer_reviews'));   
  }
 
 public function create()
 {
  return view('admin.customer_reviews.create');   
 }


  public function store(CustomerReviewRequest $request)
  {
   try{
    $addcustomer_review=CustomerReview::create([
      'customer_review' => $request['customer_review'],
      'customer_name' => $request['customer_name'],
      'job_title' => $request['job_title'],
    ]);
    return redirect()->route('customer_reviews.index')->with(['success' => 'تم الحفظ بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('customer_reviews.create')->with(['error' => 'يوجد خطأ']);

    }
  }
  

  public function edit($id)
  {
   $customer_review=CustomerReview::find($id);
   if(! $customer_review)
   {
      return redirect()->route('customer_reviews.index')->with(['error' => 'لا توجد رساله بهذا العنوان']);
    } 
    return view('admin.customer_reviews.edit',compact('customer_review'));

  }

  public function update(Request $request, $id)
  {
    try{

      $customer_review_data=CustomerReview::find($id);
      if(! $customer_review_data)
      {
        return  redirect()->route('customer_reviews.edit', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
      }
      CustomerReview::where('id',$id)->update([
        'customer_review' => $request['customer_review'],
        'customer_name' => $request['customer_name'],
        'job_title' => $request['job_title'],
      ]);

      return redirect()->route('customer_reviews.index')->with(['success' => 'تم التعديل بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('customer_reviews.index')->with(['error' => 'يوجد خطأ']);

    }
  }


  public function destroy($id)
  {
   try{

    $customer_review=CustomerReview::find($id);
    if(! $customer_review)
    {
      return  redirect()->route('customer_reviews', $id)->with(['error'=> 'خطأ لا توجد لغه ']);
    } 

    $customer_review ->delete();

      return redirect()->route('customer_reviews.index')->with(['success' => 'تم الحذف بنجاح']);
    }
    catch (\Exception $ex)
    {
      return redirect()->route('customer_reviews.index')->with(['error' => 'يوجد خطأ']);

    }
  }

}

?>

resources/views/admin/customer_reviews/create.blade.php
@extends('admin.layouts.master')
@section('css')
<!--- Internal Select2 css-->
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">

<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">أراء عملائنا</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ إضافه رأي جديد</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/customer_reviews')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض أراء عملائنا</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  إضافه رأي جديد
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                <form action="{{route('customer_reviews.store')}}" class="parsley-style-1" id="selectForm2" name="selectForm2"  method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="customer_name">
                        <label>اسم العميل: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#customer_name" name="customer_name" value="{{old('customer_name')}}" placeholder="ادخل اسم العميل" required="" type="text">
                           @error('customer_name')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="job_title">
                        <label>مهنه العميل: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#job_title" name="job_title" value="{{old('job_title')}}" placeholder="ادخل مهنه العميل" required="" type="text">
                           @error('job_title')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                    </div>
                  </div>
               
                    <div class="row mg-b-20" >
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="customer_review" >
                        <label>رأي العميل: <span class="tx-danger">*</span></label>

                        <textarea class="summernote" data-parsley-class-handler="#customer_review" required="" name="customer_review" value="{{old('customer_review')}}">
                        </textarea>


                        @error('customer_review')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                                       </div>
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">إضافه</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Select2 js -->
<script src="{{URL::asset('public/assets/plugins/select2/js/select2.min.js')}}"></script>
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script type="text/javascript">
         $('.summernote').summernote({
               height: 250,
          });
    </script>
@endsection

resources/views/admin/customer_reviews/edit.blade.php
@extends('admin.layouts.master')
@section('css')
<!--- Internal Select2 css-->
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">

<style type="text/css">
  form
  {
    margin-top: 3rem !important;
  }
  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">أراء عملائنا</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ إضافه رأي جديد</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/customer_reviews')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i> عرض أراء عملائنا</a>
            </div>
          
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

        <!-- row -->
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="main-content-label mg-b-5">
                  إضافه رأي جديد
                </div>
                <hr>
                 @if(Session::has('success'))
                <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
                @endif

                @if(Session::has('error'))
                <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
                @endif
                <form action="{{route('customer_reviews.update', $customer_review->id)}}" class="parsley-style-1" id="selectForm2" name="selectForm2"  method="POST">
                  {{ method_field('PUT') }}

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                  <div class="">
                    <div class="row mg-b-20">
                      <div class="parsley-input col-md-6" id="customer_name">
                        <label>اسم العميل: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#customer_name" name="customer_name" value="{{ $customer_review->customer_name}}" placeholder="ادخل اسم العميل" required="" type="text">
                           @error('customer_name')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="job_title">
                        <label>مهنه العميل: <span class="tx-danger">*</span></label>
                        <input class="form-control" data-parsley-class-handler="#job_title" name="job_title" value="{{ $customer_review->job_title}}" placeholder="ادخل مهنه العميل" required="" type="text">
                           @error('job_title')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                    </div>
                  </div>
               
                    <div class="row mg-b-20" >
                      <div class="parsley-input col-md-6 mg-t-20 mg-md-t-0" id="customer_review" >
                        <label>رأي العميل: <span class="tx-danger">*</span></label>

                        <textarea class="summernote" data-parsley-class-handler="#customer_review" required="" name="customer_review">
                          {{ $customer_review->customer_review}}
                        </textarea>


                        @error('customer_review')
                        <strong class="help-block" style="color:#c01f0b">{{$message}}</strong>
                        @enderror
                      </div>
                                       </div>
                <div class="mg-t-30">
                    <button class="btn btn-main-primary pd-x-20" type="submit">إضافه</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- row closed -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!--Internal  Select2 js -->
<script src="{{URL::asset('public/assets/plugins/select2/js/select2.min.js')}}"></script>
<!--Internal  Parsley.min js -->
<script src="{{URL::asset('public/assets/plugins/parsleyjs/parsley.min.js')}}"></script>
<!-- Internal Form-validation js -->
<script src="{{URL::asset('public/assets/js/form-validation.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script type="text/javascript">
         $('.summernote').summernote({
               height: 250,
          });
    </script>
@endsection

resources/views/admin/customer_reviews/index.blade.php
@extends('admin.layouts.master')
@section('css')
<!-- Internal Data table css -->
<link href="{{URL::asset('public/assets/plugins/datatable/css/dataTables.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.bootstrap4.min.css')}}" rel="stylesheet" />
<link href="{{URL::asset('public/assets/plugins/datatable/css/jquery.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/datatable/css/responsive.dataTables.min.css')}}" rel="stylesheet">
<link href="{{URL::asset('public/assets/plugins/select2/css/select2.min.css')}}" rel="stylesheet">

<style type="text/css">
  .buttons-pdf , .buttons-excel
  {
    display: none !important;
  }

  .main-content-label
  {
     font-size:large !important;
  }
  .btn-icon {
     display: initial !important;
  }
  .chk-option .checkbox-fade
  {
    display: inline-flex !important;
  }
</style>
@endsection
@section('page-header')
        <!-- breadcrumb -->
        <div class="breadcrumb-header justify-content-between">
          <div class="my-auto">
            <div class="d-flex">
              <h4 class="content-title mb-0 my-auto">الأراء</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ عرض كل الأراء</span>
            </div>
          </div>
          <div class="d-flex my-xl-auto right-content">
            <div class="pr-1 mb-3 mb-xl-0">
              <a href="{{URL('admin/customer_reviews/create')}}" class="btn btn-info btn-icon ml-2"><i class="mdi mdi-filter-variant"></i>إضافه رأي</a>
            </div>
     
          </div>
        </div>
        <!-- breadcrumb -->
@endsection
@section('content')

          <!--div-->
          <div class="col-xl-12">
            <div class="card mg-b-20">
              <div class="card-header pb-0">
                <div class="d-flex justify-content-between">
                  <h4 class="card-title mg-b-0">عرض كل الأراء</h4>
                          <a class="btn btn-info" href="{{URL('/#customer_reviews')}}">مشاهده داخل الموقع </a>

                  <i class="mdi mdi-dots-horizontal text-gray"></i>
                </div>
                <hr>
              </div>
               @if(Session::has('success'))
          <div class="alert alert-success" role="alert">{{Session::get('success')}}</div>
          @endif

          @if(Session::has('error'))
          <div class="alert alert-danger" role="alert">{{Session::get('error')}}</div>
          @endif
              <div class="card-body">
                <div class="table-responsive">
                  <table id="example" class="table key-buttons text-md-nowrap">
                    <thead>
                      <tr>
                          <th class="border-bottom-0 text-center">#</th>
                          <th class="border-bottom-0 text-center">اسم العميل</th>
                          <th class="border-bottom-0 text-center">المهنه</th>
                          <th class="border-bottom-0 text-center">رأي العميل :</th>
                          <th class="border-bottom-0 text-center">أنشأ في</th>
                          <th class="border-bottom-0 text-center">تعديل</th>
                          <th class="border-bottom-0 text-center">حذف</th>
                      </tr>
                    </thead>
                    <tbody>
                        @isset($customer_reviews)
                          @php $count = 1; @endphp
                          @foreach($customer_reviews as $data)
                          <tr>

                            <td class="text-center">{{$count}}</td>
                            <td class="text-center">{{$data->customer_name}}</td>
                            <td class="text-center">{{$data->job_title}}</td>
                            <td class="text-center">{{$data->customer_review}}</td>

                           <td class="text-center"> {{ ($data->created_at)->toDayDateTimeString()}}</td>
                           <td class="text-center">
                             <a href="{{url('admin/customer_reviews/'.$data->id.'/edit')}}" class="btn btn-primary ti-pencil-alt"></a>
                           </td>
                           <td class="text-center">
                            <form method="post" action="{{url('admin/customer_reviews/'.$data->id)}}">
                              {{csrf_field()}}
                              <a class="btn btn-danger ti-trash" data-id="{{$data->id}}" data-toggle="modal" data-target="#delete-data{{$data->id}}"></a>
                              <!-- Modal -->
                              <div class="modal modal-danger fade" id="delete-data{{$data->id}}" role="dialog">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                   <div class="modal-header" style="    display: inline;">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                    <h4 class="modal-title text-center" style="float: right;" id="exampleModalLabel">تأكيد الحذف</h4>
                                  </div>

                                  <div class="modal-body">
                                    <h5 class="text-center ">هل انت متأكد من حذف   {{$data->category_name_ar}}؟</h5>                  
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-outline"  data-dismiss="modal">إلغاء</button>
                                    <input type="hidden" name="_method" value="delete">

                                    <button class="btn btn-outline danger delete pull-right">حذف</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </form>     
                        </td>
                      </tr>
                      @php $count ++; @endphp
                      @endforeach

                      @endisset
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <!--/div-->
        </div>
        <!-- /row -->
      </div>
      <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
<!-- Internal Data tables -->
<script src="{{URL::asset('public/assets/plugins/datatable/js/jquery.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/responsive.dataTables.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/jquery.dataTables.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.buttons.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.bootstrap4.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/jszip.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/pdfmake.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/vfs_fonts.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.html5.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.print.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/buttons.colVis.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/dataTables.responsive.min.js')}}"></script>
<script src="{{URL::asset('public/assets/plugins/datatable/js/responsive.bootstrap4.min.js')}}"></script>
<!--Internal  Datatable js -->
<script src="{{URL::asset('public/assets/js/table-data.js')}}"></script>
@endsection